services:
  server:
    build:
      context: .
    image: jobs-app-image
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
        - .:/usr/src/app
        - node_modules_volume:/usr/src/app/node_modules

volumes:
  node_modules_volume: